// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3UjaopiOe6B80ZkdmnNjxKhj6oqqhOTc',
    appId: '1:449088645502:web:301558ce192e4ea3812b2f',
    messagingSenderId: '449088645502',
    projectId: 'political-app-d3125',
    authDomain: 'political-app-d3125.firebaseapp.com',
    storageBucket: 'political-app-d3125.appspot.com',
    measurementId: 'G-654WCK2BSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvyAlCmK2lS34LgDR9rFqwY2V-eIm7K8g',
    appId: '1:449088645502:android:95dac1a0fcca2005812b2f',
    messagingSenderId: '449088645502',
    projectId: 'political-app-d3125',
    storageBucket: 'political-app-d3125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTuiynWFMLzLmB2dz1E6sF7jbmvd9rJ8',
    appId: '1:449088645502:ios:0c57b8eba39f255e812b2f',
    messagingSenderId: '449088645502',
    projectId: 'political-app-d3125',
    storageBucket: 'political-app-d3125.appspot.com',
    iosBundleId: 'com.example.politicianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTuiynWFMLzLmB2dz1E6sF7jbmvd9rJ8',
    appId: '1:449088645502:ios:529152445e07cf38812b2f',
    messagingSenderId: '449088645502',
    projectId: 'political-app-d3125',
    storageBucket: 'political-app-d3125.appspot.com',
    iosBundleId: 'com.example.politicianApp.RunnerTests',
  );
}
